name: Bale Reminder

on:
  schedule:
    - cron: "30 2 * * *"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  send-reminder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/386194470839/locations/global/workloadIdentityPools/github-actions/providers/github-actions"
          service_account: "bale-reminder@bale-reminder-bot.iam.gserviceaccount.com"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests gspread google-auth

      - name: Send Bale reminder
        env:
           BALE_TOKEN: ${{ secrets.BALE_TOKEN }}
           BALE_CHAT_ID: ${{ secrets.BALE_CHAT_ID }}
           GOOGLE_SHEET_ID: "1B4IJU24LKfMeN6tpGsfO1P8zeNXIjOjjS10_4iRtkQA"
        run: python bot.py
